name: 🐞 Bug
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: textarea
    id: bug
    attributes:
      label: Bug Description
      description: What went wrong?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      value: |
        1. Go to...
        2. Click...
        3. Observe...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: OS, Browser, Node version
