name: 🧹 Chore / Refactor
description: Maintenance, refactoring, or cleanup task
title: "[Chore]: "
labels: ["chore"]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be cleaned up or refactored?
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Reason
      description: Why is this needed?
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      value: |
        - [ ] Refactor X
        - [ ] Remove dead code
        - [ ] Improve naming
